### ISSUE TITLE
Inbox chatbox: Reduce `POST` requests

### ISSUE THREAD

**Issue by linhub15** [skerkour/bloom#57]
**Problem**
Current implementation of chatbox is functioning well, but can be optimized for server performance.
Especially when self hosting on a server with limited HTTP requests / month.

Chatbox is polling `https://bloom.sh/api/inbox/queries/chatbox_messages` with non-stop POST requests to get the most updated chat messages, which adds load to the server.

**Describe the solution you'd like**
Implement chat WebSocket for sending and receiving chat messages.

**Describe alternatives you've considered**
Using SSE (Server Side Event)
* Listen to the server side event, when a new message is available then update DOM.

If using SSE, then no need to modify sending messages `send_chatbox_message`

**Additional context**
N/A

**Comment by skerkour** [comment]
Hey,
Thank you for the report!

When designing the chatbox, WebSockets and SSS were also considered but were rejected for the following reasons:
* Server with limited HTTP requests / month usually don't or have limmited support for WebSockets (AWS Lambda, Google Cloud Run, Heroku limits the number of open connections...)
* Websockets (and stateful connections) are extremely hard to scale and add a lot of moving parts, usually you have to have a pool of servers dedicated to websocket termination, a message bus between these and main the servers and so on...
* HTTP polling is extremely efficient as if done right, the HTTP request only hit an hot cache, and with Rust's speed it can be a matter of less than 1ms
* It's extremely easy to scale HTTP servers horizontally and vertically according to needs


So I believe today the easiest way to reduce POST requests is to design a smarter polling algorithm according to some metrics like `last_message`, `is_chatbox_open`, `last_interaction_time`....

I'm totally open to change my mind, but before I want the read stories about real-world websockets scaling.
