### ISSUE TITLE
Inbox (UX): Begin navigation of Vue router when HTTP requests finish

### ISSUE THREAD

**Issue by linhub15** [skerkour/bloom#58]
**Describe the bug**
When switching between Inbox, Done, Trash and Spam the web requests takes some time to resolve.
The route and background color of the navigation link is changed before loading the data on the component
which creates a feeling of lag.

Symptom
* the background color is instantly applied on click of the navigation link whether or not the chat messages have loaded or not.
* the url path is instantly applied on click of the navigation whether or not the chat messages loaded successfully or not.

**To Reproduce**

Pre-condition:
* have message A in `/inbox`
* have message B in `/inbox/done`

1. Go to `/inbox`
2. Go to `/inbox/done`

**Expected behavior**
Desktop
* Expect navigation to occur when HTTP request completes with `200 OK`.
* Expect background color of navigation link to occur when HTTP request completes with `200 OK`.

Smartphone
* Expect all chats to be cleared onclick before loading the appropriate ones

**Additional context**
We can compare this with the primary competitor "Gmail".
In Gmail, when selecting Inbox -> Sent -> Inbox, we can see that the navigation link background colors and url paths are not updated until the little "loading" text has disappeared.

They are waiting for the web request to complete before navigating using some form of router navigation guard, that loads first before navigating.

**Comment by skerkour** [comment]
Thank you for this awesomely detailed report!

I've added the issue on the current roadmap (https://github.com/skerkour/bloom/projects/3) and I hope to be able to fix it before the end of the week.
