### ISSUE TITLE
Twitter @sylvain_kerkour is offline

### ISSUE THREAD

**Issue by pflegende** [skerkour/bloom#71]
**Describe the bug**
on your site:

https://bloom.sh/contact 

works not on twitter link
https://twitter.com/sylvain_kerkour

twitter handle is offline

**Expected behavior**
Hoping you are healthy!
(THIS was the useCase for this issue.
;)

We "pflegende" are back on bloom, also after the project restart.

**Screenshots**
![Opera Momentaufnahme_2021-10-04_193113_twitter com](https://user-images.githubusercontent.com/52720420/135898075-617c5abf-ed2c-496d-9657-0f3e94e14804.png)

**Additional context**
Thx for the great dataSaving tool in the "old" bloom.
CU
KEEP HEALTHY
:+1:

**Comment by skerkour** [comment]
Thank you very much 🙏

Fixed in 67b4f98, should be online in a few hours :)

**Comment by pflegende** [comment]
😃 
CU on Twitter
