### ISSUE TITLE
rust_fast_port_scanner returns all ports

### ISSUE THREAD

**Issue by claudiociardelli** [skerkour/bloom#72]
Hello Sylvain,
I tested rust_fast_port_scanner today. Not sure if this is an issue or a lack of understanding from me:
I run the program with the IP address of my linux server to check what ports might be listening to requests.
so I ran the command like this:
<pre>
./target/release/rust_fast_port_scanner 192.168.1.70
</pre>
I will not print the result here, But I get 1002 rows in the result so, all the ports tested.

However when I check what ports are listening as per  https://www.techrepublic.com/article/how-to-locate-and-close-an-open-port-in-linux/
I only see 6 open ports
<pre>
coco@dev01:~/projects/kerkour.com/2021/rust_fast_port_scanner$ sudo ss -tulwn | grep LISTEN
tcp   LISTEN 0      511                            127.0.0.1:41683      0.0.0.0:*

tcp   LISTEN 0      4096                       127.0.0.53%lo:53         0.0.0.0:*

tcp   LISTEN 0      128                              0.0.0.0:22         0.0.0.0:*

tcp   LISTEN 0      100                              0.0.0.0:25         0.0.0.0:*

tcp   LISTEN 0      100                                 [::]:25            [::]:*
</pre>

**Comment by skerkour** [comment]
I've moved the issue to the good repository :)
