### ISSUE TITLE
is this clone() required ?

### ISSUE THREAD

**Issue by sternix** [skerkour/bloom#80]
https://github.com/skerkour/bloom/blob/main/bloom/libs/stdx/src/mail/mod.rs#L43

is this clone() required ?

        let address = self.address.clone();
        write!(f, "{} <{}>", name, address)

-> 

        write!(f, "{} <{}>", name, self.address)

**Comment by sigaloid** [comment]
Not anymore, but it seems like it used to be required: https://blog.rust-lang.org/2021/05/11/edition-2021.html#disjoint-capture-in-closures

**Comment by sternix** [comment]
Thanks,
